Update linux-musl.yml

diff --git a/.github/workflows/linux-musl.yml b/.github/workflows/linux-musl.yml
--- a/.github/workflows/linux-musl.yml
+++ b/.github/workflows/linux-musl.yml
@@ -2,22 +2,13 @@ name: Linux Build Alpine
 on:
   push:
     paths-ignore:
-      - docs/**
-      - "**.md"
-      - changelog.txt
-      - LEGAL
-      - LICENSE
-      - .github/**
-      - "!.github/workflows/linux.yml"
-      - snap/**
-      - Telegram/build/**
-      - Telegram/Resources/uwp/**
-      - Telegram/Resources/winrc/**
-      - Telegram/SourceFiles/platform/win/**
-      - Telegram/SourceFiles/platform/mac/**
-      - Telegram/Telegram/**
-      - Telegram/configure.bat
-      - Telegram/Telegram.plist
+      - 'docs/**'
+      - '**.md'
+      - 'changelog.txt'
+      - 'LEGAL'
+      - 'LICENSE'
+      - '.github/**'
+      - '!.github/workflows/linux.yml'
   workflow_dispatch:
 
 jobs:
@@ -26,7 +17,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       UPLOAD_ARTIFACT: "true"
-      BUILD_TYPE: Release
+      BUILD_TYPE: MinSizeRel
       TDLIB_COMMIT: 369ee922b45bfa7e8da357e4d62e93925862d86d
     
     container: 
@@ -43,20 +34,16 @@ jobs:
                   opus-dev alsa-lib-dev pulseaudio-dev boost-dev \
                   fmt-dev abseil-cpp-dev ffmpeg-dev gobject-introspection-dev \
                   libdispatch-dev gsl-dev hunspell-dev lz4-dev minizip-dev \
-                  msgsl openal-soft-dev openssl-dev>3 range-v3-dev \
+                  msgsl openal-soft-dev "openssl-dev>3" range-v3-dev \
                   rnnoise-dev tl-expected wayland-dev libxcb-dev \
                   xcb-util-keysyms-dev xxhash-dev zlib-dev libavif-dev \
-                  libheif-dev libjxl-dev libvpx-dev protobuf-dev
+                  libheif-dev libjxl-dev libvpx-dev protobuf-dev \
+                  qt6-qtimageformats font-opensans
 
       - name: Clone
         uses: actions/checkout@v4
         with:
           submodules: recursive
-
-      - name: Free up disk space
-        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
-        with:
-          tool-cache: true
 
       - name: Fetch TDLib
         run: |
@@ -64,50 +51,48 @@ jobs:
           tar -xzf ${{ env.TDLIB_COMMIT }}.tar.gz
           mv td-${{ env.TDLIB_COMMIT }} td
 
+      - name: Build TDLib
+        run: |
+          export LDFLAGS="$LDFLAGS -Wl,-z,stack-size=1024768"
+          cmake -S td -B td/build \
+                -DCMAKE_BUILD_TYPE=None \
+                -DCMAKE_INSTALL_PREFIX="$PWD/td/install" \
+                -Wno-dev \
+                -DTD_E2E_ONLY=ON
+          cmake --build td/build
+          cmake --install td/build
+
       - name: Build Telegram Desktop
         run: |
           export LDFLAGS="$LDFLAGS -Wl,-z,stack-size=1024768"
+          export CFLAGS="$CFLAGS -O2 -march=x86-64 -mtune=generic"
+          export CXXFLAGS="$CXXFLAGS -O2 -march=x86-64 -mtune=generic"
           
-          cmake -S td -B td/build -DCMAKE_BUILD_TYPE=Release \
-                -DCMAKE_INSTALL_PREFIX="$PWD/td/install" -DTD_E2E_ONLY=ON
-          cmake --build td/build --target install
-
-          cmake -B out/${{ env.BUILD_TYPE }} -G Ninja . \
+          cmake -B out -G Ninja . \
+            -DCMAKE_INSTALL_PREFIX=/usr \
             -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
-            -DCMAKE_C_FLAGS_RELEASE='-O3 -s -march=x86-64 -mtune=generic' \
-            -DCMAKE_CXX_FLAGS_RELEASE='-O3 -s -march=x86-64 -mtune=generic' \
             -DCMAKE_COMPILE_WARNING_AS_ERROR=OFF \
             -DTDESKTOP_API_ID=${{ secrets.TELEGRAM_API_ID }} \
             -DTDESKTOP_API_HASH=${{ secrets.TELEGRAM_API_HASH }} \
-            -DTDESKTOP_API_TEST=OFF \
             -DDESKTOP_APP_DISABLE_AUTOUPDATE=ON \
             -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
             -DDESKTOP_APP_USE_PACKAGED=ON \
             -Dtde2e_DIR="$PWD/td/install/lib/cmake/tde2e"
           
-          cmake --build out/${{ env.BUILD_TYPE }}
+          cmake --build out
 
-      - name: Strip binaries
+      - name: Verify and Strip
         run: |
-          find out/${{ env.BUILD_TYPE }} -type f -executable -exec strip --strip-all {} \;
+          BINARY_PATH=$(find out/ -type f -executable -name Telegram -o -name telegram-desktop | head -n 1)
+          if [ -z "$BINARY_PATH" ]; then echo "Binary not found"; exit 1; fi
+          strip --strip-all "$BINARY_PATH"
+          mkdir -p artifact
+          cp "$BINARY_PATH" artifact/Telegram
+          echo "FINAL_BIN=artifact/Telegram" >> $GITHUB_ENV
 
-      - name: Verify build
-        run: |
-          filePath=$(find out/${{ env.BUILD_TYPE }} -name Telegram -type f)
-          if [ -z "$filePath" ]; then filePath=$(find out/${{ env.BUILD_TYPE }} -name telegram-desktop -type f); fi
-          
-          if [ -f "$filePath" ]; then
-            echo "Build successfully done!"
-            ls -lh "$filePath"
-            echo "BIN_PATH=$filePath" >> $GITHUB_ENV
-          else
-            echo "Build error: binary not found"
-            exit 1
-          fi
-
-      - name: Package and Upload
+      - name: Upload Artifact
         if: env.UPLOAD_ARTIFACT == 'true'
         uses: actions/upload-artifact@v4
         with:
-          name: Telegram-Alpine-Musl
-          path: ${{ env.BIN_PATH }}
+          name: Telegram-Alpine-Musl-Core2Duo
+          path: artifact/
